server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: biometrics-service
          uri: lb://BIOMETRICS-SERVICE
          predicates:
            - Path=/biometrics/**
        - id: turnstile-service
          uri: lb://TURNSTILE-SERVICE
          predicates:
            - Path=/turnstile/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
